contact/urls.py
from django.urls import path
from . import views

urlpatterns = [
     path('', views.ContactUs.as_view(), name='contact'),
]

foodiefavourites/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePageView.as_view(), name='home'),
    path("restaurants/", include("restaurants.urls"), name="restaurant_urls"),
    path("accounts/", include("accounts.urls"), name="account_urls"),
    path("contact/", include("contact.urls"), name="contact_urls"),
]


handler404 = views.handler404
handler500 = views.handler500

restaurants/urls.py
from django.urls import path
from . import views

urlpatterns = [
     path('', views.RestaurantList.as_view(), name='restaurants'),
     path('add/', views.AddRestaurant.as_view(),
          name='add_restaurant'),
     path('<slug:slug>/edit/', views.EditRestaurant.as_view(),
          name='edit_restaurant'),
     path('<slug:slug>/delete/', views.DeleteRestaurant.as_view(),
          name='delete_restaurant'),
     path('<slug:slug>/', views.RestaurantDetail.as_view(),
          name='restaurant_detail'),
     path('favourited/<slug:slug>/', views.RestaurantFavourite.as_view(),
          name='restaurant_favourited'),
]

restaurants/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.text import slugify
from cloudinary.models import CloudinaryField


class Cuisine(models.Model):
    name = models.CharField(max_length=50)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class Restaurant(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='restaurant_posts')
    author_slug = models.SlugField(max_length=100)
    updated_on = models.DateTimeField(auto_now=True)
    created_on = models.DateTimeField(auto_now_add=True)
    description = models.TextField()
    image = CloudinaryField('image', default='default')
    rating = models.IntegerField()
    favourited = models.ManyToManyField(
        User, related_name='restaurant_favourited', blank=True)
    location = models.CharField(max_length=200)
    county = models.CharField(max_length=200)
    cuisine = models.ManyToManyField(
        Cuisine, related_name='restaurant_cuisine', blank=False)
    approved = models.BooleanField(default=True)

    class Meta:
        ordering = ['-created_on']

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.author_slug = self.author.profile.slug
        super(Restaurant, self).save(*args, **kwargs)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('restaurant_detail', kwargs={'slug': self.slug})

    def number_of_favourites(self):
        return self.favourited.count()

    def list_cuisines(self):
        cuisine_string = ""
        for cuisine in self.cuisine.all():
            cuisine_string += str(cuisine) + ", "

        return cuisine_string[:len(cuisine_string)-2]


class Comment(models.Model):
    restaurant = models.ForeignKey(
        Restaurant, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=100)
    name_slug = models.SlugField(max_length=100)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']
    
    def save(self, *args, **kwargs):
        self.name_slug = slugify(self.name)
        super(Comment, self).save(*args, **kwargs)

    def __str__(self):
        return f"Comment {self.content} by {self.name}"


class Dish(models.Model):
    restaurant = models.ForeignKey(
        Restaurant, on_delete=models.CASCADE, related_name='dishes')
    name = models.CharField(max_length=100)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

restaurants/forms.py
from django import forms
from localflavor.gb.gb_regions import GB_REGION_CHOICES
from . import models

RATING_CHOICES = [tuple([x, x]) for x in range(1, 6)]
GB_REGION_CHOICES = (('', ''),) + GB_REGION_CHOICES


class AddRestaurantForm(forms.ModelForm):
    class Meta:
        model = models.Restaurant
        fields = ('name', 'description', 'image', 'rating', 'location', 'county', 'cuisine')
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['description'].widget.attrs['rows'] = 4
        self.fields['rating'].widget = forms.Select(choices=RATING_CHOICES)
        self.fields['location'].label = 'Location (city / town / village)'
        self.fields['county'].widget = forms.Select(choices=GB_REGION_CHOICES)
        self.fields['cuisine'].label = 'Cuisine (select "Other" if missing)'


class CommentForm(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ('content',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['content'].label = False
        self.fields['content'].widget.attrs['placeholder'] = 'Leave a comment...'
        self.fields['content'].widget.attrs['rows'] = 2

restaurants/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.urls import reverse_lazy
from django.views import generic, View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from foodiefavourites.settings import EMAIL_HOST_USER
from .models import Cuisine, Restaurant, Comment, Dish
from .forms import AddRestaurantForm, CommentForm


class RestaurantList(generic.ListView):
    """
    Restaurant List class based view to show Restaurant model on
    restaurants.html
    """
    model = Restaurant
    queryset = Restaurant.objects.filter(approved=True).order_by('-created_on')
    template_name = 'restaurants.html'
    paginate_by = 3
    restaurant_cuisines = {}
    restaurant_cuisines_count = 0
    restaurant_locations = {}
    restaurant_locations_count = 0

    def get_queryset(self):
        cuisine_filter = self.request.GET.get('cuisine-filter')
        location_filter = self.request.GET.get('location-filter')
        search_restaurants = self.request.GET.get('search-restaurants')

        if (cuisine_filter != '' and cuisine_filter is not None and
                cuisine_filter != 'All'):
            self.queryset = self.queryset.filter(cuisine__name=cuisine_filter)

        if (location_filter != '' and location_filter is not None and
                location_filter != 'All'):
            self.queryset = self.queryset.filter(
                county__icontains=location_filter)

        if search_restaurants != '' and search_restaurants is not None:
            self.queryset = self.queryset.filter(
                name__icontains=search_restaurants)

        return self.queryset

    def set_cuisine_and_location_context(self, restaurants):
        """
        Sets cuisine and location related variables to be used as context
        for the filters section of restaurants.html
        """
        location_filter = self.request.GET.get('location-filter')
        cuisine_string = ''

        if (location_filter == 'All' or location_filter == '' or
                location_filter is None):
            for restaurant in restaurants:
                cuisine_string += restaurant.list_cuisines() + ', '
        else:
            for restaurant in restaurants:
                if restaurant.county == location_filter:
                    cuisine_string += restaurant.list_cuisines() + ', '

        if cuisine_string != '':
            cuisine_string = cuisine_string[:len(cuisine_string)-2]
            cuisine_list = cuisine_string.split(', ')
        else:
            cuisine_list = []

        restaurant_cuisines = {}
        restaurant_cuisines_count = 0

        for cuisine in cuisine_list:
            restaurant_cuisines_count += 1
            if cuisine not in restaurant_cuisines:
                restaurant_cuisines[cuisine] = 1
            else:
                restaurant_cuisines[cuisine] = restaurant_cuisines[cuisine] + 1

        cuisine_filter = self.request.GET.get('cuisine-filter')
        restaurant_locations = {}
        restaurant_locations_count = 0

        if (cuisine_filter == 'All' or cuisine_filter == '' or
                cuisine_filter is None):
            for restaurant in restaurants:
                restaurant_locations_count += 1
                if restaurant.county not in restaurant_locations:
                    restaurant_locations[restaurant.county] = 1
                else:
                    restaurant_locations[
                        restaurant.county] = restaurant_locations[
                            restaurant.county] + 1
        else:
            for restaurant in restaurants:
                if cuisine_filter in restaurant.list_cuisines():
                    restaurant_locations_count += 1
                    if restaurant.county not in restaurant_locations:
                        restaurant_locations[restaurant.county] = 1
                    else:
                        restaurant_locations[
                            restaurant.county] = restaurant_locations[
                                restaurant.county] + 1

        self.restaurant_cuisines = restaurant_cuisines
        self.restaurant_cuisines_count = restaurant_cuisines_count
        self.restaurant_locations = restaurant_locations
        self.restaurant_locations_count = restaurant_locations_count

    def get_context_data(self, **kwargs):
        """
        Sets context data to be used in restaurants.html
        """
        context = super(RestaurantList, self).get_context_data(**kwargs)

        restaurants = Restaurant.objects.filter(approved=True)
        search_restaurants = self.request.GET.get('search-restaurants')

        if search_restaurants != '' and search_restaurants is not None:
            restaurants = restaurants.filter(
                name__icontains=search_restaurants)

        self.set_cuisine_and_location_context(restaurants)

        # Creates copy of GET and removes superfluous additonal 'page' that is
        # added to the url when using pagination and filters.
        # CREDIT = idea came from: (https://stackoverflow.com/questions/
        # 59972694/django-pagination-maintaining-filter-and-order-by)
        get_copy = self.request.GET.copy()
        if get_copy.get('page'):
            get_copy.pop('page')

        context['cuisine_count'] = self.restaurant_cuisines_count
        context['cuisine_list'] = self.restaurant_cuisines
        context['location_count'] = self.restaurant_locations_count
        context['location_list'] = self.restaurant_locations
        context['range'] = range(5)
        context['get_copy'] = get_copy
        return context


class RestaurantDetail(View):
    """
    Restaurant Detail class based view to show individual Restaurant model
    objects on restaurant_detail.html
    """
    def get(self, request, slug, *args, **kwargs):
        # CREDIT - idea for get method structure came from
        # Code Institute's blog walkthrough project
        queryset = Restaurant.objects.filter(approved=True)
        restaurant = get_object_or_404(queryset, slug=slug)
        dishes = restaurant.dishes.order_by('name')
        comments = restaurant.comments.filter(
            approved=True).order_by('created_on')
        comment_count = restaurant.comments.filter(approved=True).count()
        liked = False
        if restaurant.favourited.filter(id=self.request.user.id).exists():
            liked = True

        return render(
            request,
            'restaurant_detail.html',
            {
                'restaurant': restaurant,
                'range': range(5),
                'dishes': dishes,
                'comments': comments,
                'commented': False,
                'comment_count': comment_count,
                'comment_form': CommentForm(),
                'liked': liked,
            },
        )

    def post(self, request, slug, *args, **kwargs):
        # CREDIT - idea for post method structure came from
        # Code Institute's blog walkthrough project
        queryset = Restaurant.objects.filter(approved=True)
        restaurant = get_object_or_404(queryset, slug=slug)
        dishes = restaurant.dishes.order_by('name')
        comments = restaurant.comments.filter(
            approved=True).order_by('created_on')
        comment_count = restaurant.comments.filter(approved=True).count()
        liked = False
        if restaurant.favourited.filter(id=self.request.user.id).exists():
            liked = True

        comment_form = CommentForm(data=request.POST)

        if comment_form.is_valid():
            comment_form.instance.email = request.user.email
            comment_form.instance.name = request.user.username
            comment = comment_form.save(commit=False)
            comment.restaurant = restaurant
            comment.save()
            email_subject = ('Comment from: ' + comment_form.instance.name +
                             ' - Foodie Favourites')
            email_message = ('A comment on "' + str(restaurant) +
                             ' "has been submitted and needs approval.')

            send_mail(
                email_subject,
                email_message,
                EMAIL_HOST_USER,
                [EMAIL_HOST_USER],
                fail_silently=False,
            )
        else:
            comment_form = CommentForm()

        return render(
            request,
            'restaurant_detail.html',
            {
                'restaurant': restaurant,
                'range': range(5),
                'dishes': dishes,
                'comments': comments,
                'commented': True,
                'comment_count': comment_count,
                'comment_form': CommentForm(),
                'liked': liked,
            },
        )


class AddRestaurant(LoginRequiredMixin, CreateView):
    """
    Class based view used for adding restaurant objects via the
    add restaurant form on add_restaurant.html
    """
    model = Restaurant
    template_name = 'add_restaurant.html'
    form_class = AddRestaurantForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        form.save_m2m()

        dishes = self.request.POST['dishes-string'].split(',')
        for dish in dishes:
            Dish.objects.create(
                restaurant=Restaurant.objects.get(id=self.object.id),
                name=dish
            ).save()

        messages.add_message(
            self.request,
            messages.SUCCESS,
            f'"{self.object.name}" has been added.')

        return super().form_valid(form)


class EditRestaurant(LoginRequiredMixin, UpdateView):
    """
    Class based view used for editing restaurant objects via the

templates/add_restaurant.html
{% extends "base_heading_split.html" %}

{% load crispy_forms_tags %}

{% block bg_image %}
<div class="bg-img bg-img-add-restaurant"></div>
{% endblock %}

{% block heading %}
{% if request.get_full_path == '/restaurants/add/' %}
Add Restaurant
{% else %}
Edit Restaurant
<a href="{% url 'delete_restaurant' restaurant.slug %}" class="link-custom text-capitalize delete-link">(Delete)</a>
{% endif %}
{% endblock %}

{% block left %}
<!-- Add restaurant main form -->
{% if request.get_full_path == '/restaurants/add/' %}
<form class="add-restaurant-form" action="{% url 'add_restaurant' %}" method="post" enctype="multipart/form-data">
    {% else %}
    <form class="add-restaurant-form" action="{% url 'edit_restaurant' restaurant.slug %}" method="post"
        enctype="multipart/form-data">
        {% endif %}
        {% csrf_token %}
        {{ form | crispy }}
        {% endblock %}

        {% block right %}
        <!-- Dishes section -->
        <h4 class="text-center">Favourite Dishes</h4>

        <label for="dishes-input">Add dishes*</label>
        <input type="text" name="dishes-input" id="dishes-input" class="form-control">
        <div class="row">
            <button class="col-6 col-sm-4 col-md-5 col-xxl-4 mt-2 mx-auto px-0 px-sm-2 btn btn-light rounded-3"
                id="add-dish-button">Add Dish</button>
        </div>
        <input type="text" name="dishes-string" id="dishes-string" aria-label="Input to contain dishes string. Is not visible " required>

        <div class="row justify-content-evenly favourite-dishes">
            <div class="col-sm-8">
                <ul class="my-4 p-0" id="dishes-container">
                    {% if request.get_full_path != '/restaurants/add/' %}
                    {% for dish in dishes %}
                    <li
                        class="dish d-flex justify-content-between my-3 py-2 px-3 bg-lighter-dark-custom text-light-custom rounded-3 box-shadow-custom">
                        <span class="name text-start">{{ dish.name }}</span>
                        <span onclick="removeDish(this)" class="btn-remove text-end" role="button">X</span>
                    </li>
                    {% endfor %}
                    {% endif %}
                </ul>

            </div>
        </div>
        <hr class="hr-custom m-0">
        <div class="d-flex justify-content-center pt-4">
            {% if request.get_full_path == '/restaurants/add/' %}
            <button type="submit" class="btn btn-light">Submit Restaurant</button>
            {% else %}
            <button type="submit" class="btn btn-light">Update Restaurant</button>
            {% endif %}
        </div>
    </form>
    {% endblock %}

templates/base_confirm.html
{% extends "base.html" %}

{% block content %}

{% block bg_image %}
{% endblock bg_image %}

<div class="container-fluid">
    <div class="row justify-content-center my-5">
        <div class="col-10 col-sm-8 col-lg-6 col-xxl-4 py-4 px-5 bg-dark text-light-custom rounded-3 box-shadow-custom">
            <div class="row">
                <div class="col ps-xxl-4">
                    <h1>
                        {% block heading %}
                        {% endblock heading %}
                    </h1>

                    {% block section_content %}
                    {% endblock section_content %}
                </div>
            </div>

        </div>
    </div>
</div>

{% endblock %}

templates/base_heading.html
{% extends "base.html" %}

{% block content %}

{% block bg_image %}
{% endblock bg_image %}

<div class="container-fluid mw-1600px base-heading-container">
    <div class="row justify-content-center my-5">
        <div class="col-10 col-lg-8 p-5 bg-dark text-light-custom rounded-3 box-shadow-custom">

            <h3 class="text-center text-uppercase pb-4 border-bottom border-light border-1 position-relative text-break">
                {% block heading %}
                {% endblock heading %}
            </h3>

            {% block section_content %}
            {% endblock section_content %}

        </div>
    </div>
</div>


{% endblock %}

templates/base_heading_split.html
{% extends "base_heading.html" %}

{% block section_content %}

<div class="row g-0 mt-4 py-2">
    <div class="col-12 col-md-6 mb-3 mb-md-0 px-md-2 border-end border-light border-1">
        <div class="row justify-content-center mx-auto">
            <div class="col-12 col-xxl-10 position-relative">
                {% block left %}
                {% endblock left %}
            </div>
        </div>
    </div>

    <div class="col-12 col-md-6 pt-3 pt-md-0 px-md-2 border-top border-light border-1">
        <div class="row justify-content-center mx-auto ps-md-3">
            <div class="col-12 col-xxl-10 position-relative">
                {% block right %}
                {% endblock right %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/contact_us.html
{% extends "base_heading.html" %}

{% load crispy_forms_tags %}

{% block bg_image %}
<div class="bg-img bg-img-contact"></div>
{% endblock %}

{% block heading %}
Contact Us
{% endblock %}

{% block section_content %}
<form class="contact-us-form mt-3 mx-auto mw-lg-600px" action="{% url 'contact' %}" method="post">
    {% csrf_token %}
    {{ form | crispy }}
    <hr class="hr-custom mt-3 mb-0">
    <div class="d-flex justify-content-center pt-4">
        <button type="submit" class="btn btn-light">Submit</button>
    </div>
</form>
{% endblock %}

templates/edit_profile.html
{% extends "base_heading.html" %}

{% load crispy_forms_tags %}

{% block bg_image %}
<div class="bg-img bg-img-edit-profile"></div>
{% endblock %}

{% block heading %}
Edit Profile
{% endblock %}

{% block section_content %}
<form class="update-profile-form mt-3 mx-auto mw-lg-600px" action="{% url 'edit_profile' user.username %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form | crispy }}
    <hr class="hr-custom mt-3 mb-0">
    <div class="d-flex justify-content-center pt-4">
        <button type="submit" class="btn btn-light">Update Profile</button>
    </div>
</form>
{% endblock %}

templates/filters.html
<div class="row justify-content-center page-title">
    <div class="col-10 mb-1 p-2 text-light">
        <h4 class="text-center m-1">Filters</h4>
        <hr class="m-1">
        
        <!-- Cuisine List -->
        <h5 class="mt-4 ps-2">Cuisine</h5>
        <ul class="list-group rounded-3">
            <li class="list-group-item d-flex justify-content-between align-items-start cuisine-item">
                <div class="ms-2 me-auto">
                    <div class="cuisine-name">All</div>
                </div>
                <span class="badge bg-dark rounded-pill">{{ cuisine_count }}</span>
            </li>
            {% for key, value in cuisine_list.items %}
            <li class="list-group-item d-flex justify-content-between align-items-start cuisine-item">
                <div class="ms-2 me-auto">
                    <div class="cuisine-name">{{ key }}</div>
                </div>
                <span class="badge bg-dark rounded-pill">{{ value }}</span>
            </li>
            {% endfor %}
        </ul>

        <!-- Location list -->
        <h5 class="mt-4 ps-2">Location</h5>
        <ul class="list-group rounded-3">
            <li class="list-group-item d-flex justify-content-between align-items-start location-item">
                <div class="ms-2 me-auto">
                    <div class="location-name">All</div>
                </div>
                <span class="badge bg-dark rounded-pill">{{ location_count }}</span>
            </li>
            {% for key, value in location_list.items %}
            <li class="list-group-item d-flex justify-content-between align-items-start location-item">
                <div class="ms-2 me-auto">
                    <div class="location-name">{{ key }}</div>
                </div>
                <span class="badge bg-dark rounded-pill">{{ value }}</span>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>

templates/restaurants.html
{% extends "base.html" %}

{% load static %}

{% block content %}

<div class="bg-img bg-img-restaurant"></div>

<div class="container-fluid mw-1600px">
    
    <div class="row w-sm-75 w-xl-100 mt-4 mb-3 my-xl-4 mx-auto justify-content-evenly fs-small-custom">
        <button class="d-xl-none col-4 col-lg-3 btn bg-lighter-dark-custom text-white box-shadow-custom rounded-pill"
            data-bs-toggle="modal" data-bs-target="#filtersModal">Fliters</button>
        {% if user.is_authenticated %}
        <div class="d-none d-xl-block col-xl-3"></div>
        <div class="d-flex col-4 col-lg-3 col-xl-7 p-0 justify-content-center fs-small-custom">
            <a href="{% url 'add_restaurant' %}"
                class="w-100 w-xl-25 btn bg-lighter-dark-custom text-white box-shadow-custom rounded-pill">Add
                Restaurant</a>
        </div>
        {% endif %}
    </div>
    <div class="row justify-content-evenly mx-auto">
        <div class="d-none d-xl-block col-xl-3 mb-5 py-4 bg-dark rounded-3 box-shadow-custom h-100">

            {% include "filters.html" %}

            <!-- Form used for Cuisine and Location filters -->
            <form id="filter-form" action="{% url 'restaurants' %}" method="get">
                <input type="hidden" name="cuisine-filter" id="cuisine-filter" value="All">
                <input type="hidden" name="location-filter" id="location-filter" value="All">
                <input type="hidden" name="search-restaurants" id="search-restaurants">
            </form>
        </div>
        <div class="col-10 col-lg-8 col-xl-7 mb-5 py-4 bg-dark rounded-3 box-shadow-custom">
            <div class="row justify-content-center page-title">
                <div class="col-8 col-sm-5 col-md-4 mb-1 p-2 text-light">
                    <h2 class="text-center m-1">Restaurants</h2>
                    <hr class="m-1">
                </div>
            </div>

            <!-- Search bar -->
            <div class="row g-0 justify-content-center mt-3 mb-2">
                <div class="col-10 py-2 px-3 bg-lighter-dark-custom rounded-3 box-shadow-custom">
                    <div class="row g-0 justify-content-center">
                        <input class="col-11 col-md-8 me-md-2 py-2 px-3 rounded-3" id="search-input"
                            placeholder="Search restaurants..." aria-label="Search" type="search">
                        <button class="col-4 col-md-2 mt-1 mt-md-0 px-0 px-sm-3 btn btn-light rounded-3"
                            id="search-button">Search</button>
                    </div>
                </div>
            </div>
            
            <!-- Restaurants List -->
            {% for restaurant in restaurant_list %}
            <div class="row justify-content-center">
                <div class="col-10">
                    <div class="card my-4 card-custom box-shadow-custom text-center">
                        <div class="row g-0">
                            <div class="col-md-4 h-md-250px">
                                <a href="{% url 'restaurant_detail' restaurant.slug %}">
                                    {% if "default" in restaurant.image.url %}
                                    <img src="{% static 'images/default-restaurant.jpg' %}"
                                        class="img-fluid rounded card-image" alt="Default image for restaurants posts">
                                    {% else %}
                                    <img class="img-fluid rounded card-image" src="{{ restaurant.image.url }}"
                                        alt="Uploaded image for restaurant's post">
                                    {% endif %}
                                </a>
                            </div>
                            <div class="col-md-8 d-flex align-items-center h-md-250px">
                                <div class="card-body text-break">
                                    <a href="{% url 'restaurant_detail' restaurant.slug  %}" class="link-custom">
                                        <h4 class="card-title">{{ restaurant.name }}</h4>
                                    </a>
                                    <p class="card-text">
                                        Added by
                                        <a href="{% url 'profile' restaurant.author_slug %}"
                                            class="link-custom">{{ restaurant.author }}</a>
                                        on {{ restaurant.created_on }}
                                    </p>
                                    <p class="card-text">Cuisine: {{ restaurant.list_cuisines }}</p>
                                    <p class="card-text">Location: {{ restaurant.county }}</p>
                                    <div class="d-flex justify-content-between mt-3 mb-0 favourties-rating">
                                        <span class="favourites-span ms-3 ms-sm-5">
                                            {% if user in restaurant.favourited.all %}
                                            <i class="fas fa-heart"></i>
                                            {% else %}
                                            <i class="far fa-heart"></i>
                                            {% endif %}
                                            {{ restaurant.number_of_favourites }}
                                        </span>
                                        <span class="rating-span me-3 me-sm-5">
                                            {% for i in range %}
                                            {% if restaurant.rating > i %}
                                            <i class="fas fa-star"></i>
                                            {% else %}
                                            <i class="far fa-star"></i>
                                            {% endif %}
                                            {% endfor %}
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% empty %}
            <h4 class="my-4 text-center text-light-custom">No restaurants match your search.</h4>
            {% endfor %}

            <!-- Pagination -->
            {% if is_paginated %}
            <nav aria-label="Page navigation">
                <ul class="pagination justify-content-center my-2">
                    <!-- CREDIT https://nemecek.be/blog/105/how-to-use-elided-pagination-in-django-and-solve-too-many-pages-problem -->
                    {% for i in page_range|default_if_none:page_obj.paginator.get_elided_page_range %}
                    {% if page_obj.number == i %}
                    <li class="active page-item">
                        <span class="page-link">{{ i }} <span class="sr-only">(current)</span></span>
                    </li>
                    {% else %}
                    {% if i == page_obj.paginator.ELLIPSIS %}
                    <li class="page-item"><span class="page-link">{{ i }}</span></li>
                    {% else %}
                    <li class="page-item"><a class="page-link bg-light text-dark fw-bold"
                            href="?page={{ i }}&{{ get_copy.urlencode }}">{{ i }}</a></li>
                    {% endif %}
                    {% endif %}
                    {% endfor %}
                    <!-- END CREDIT -->
                </ul>
            </nav>
            {% endif %}
        </div>
    </div>
</div>

<!-- Filter modal -->
<div class="modal fade" id="filtersModal" tabindex="-1" aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content mb-5 py-4 bg-dark rounded-3">
            <span id="modalLabel" class="d-none">Model for cuisine and location filters</span>
            <button type="button" class="bg-lighter-dark-custom text-white fw-bold close-model-button"
                data-bs-dismiss="modal" aria-label="Close modal">&times;</button>
            {% include "filters.html" %}
        </div>
    </div>
</div>

{% endblock %}